Using OOP in Python - 1st project. Ortal Lasry.

The project's name: Cosmetic Correspondance התאמה קוסמטית

In this project the target is to find a compatible product for a certain user, by using the product's benefit and comparing it to the user's skin concern.
The benefit and skin concern must meet a complete comparison, the strings should be the same.
From this point of comparison, we can achieve the suitable product per user.

At the beggining of the program, a user needs to prompt his details (containing his skin concern) and can also add a product stating what is the product's benefit, meaning - what skin concern will it improve.
Once this is done, the user will be asked if he wants to know what product fits their skin concern, once clicking yes then the corresponding product will be printed to the console stating its ingredient.

Later on, my plan is to expand this program into a Cosmetic Calculator which will give a list of ingredients suitable for a user according his skin concerns using the knowledge stored in a JSON file (which will be rewritten while running the program with several users and their products recommendation which includes the ingredient in each product).
The final straw will be for the user to be asked if he wants to make a new product on his own with recommended ingredients, once clicking yes then he will get the list of ingredients with their range of percentages used.
This could also be used later on by reserchers who want to improve their cosmetic products based on this data set and program.

I will add that i have no prior knowledge to this course and so I have used AI while implementing my code and ideas, guiding the AI through how i visualize the code (a.k.a dictionaries, classes, working enviroment and etc.). The AI was used only in the purpose of learning and achieving the final goal of the program. I have thought of implementing a JSON file but still need more practice so i will try to implement this also. through AI i have learned how to build JSON from scratch and storing data but i got stuck because this part is still new to me.

Thank you for taking the time to read this and hope you will enjoy prompting this program.

Ortal Lasry (no, i haven't used AI to write this paragraph :)

Note: The final code is at the bottom. all the other blocks were tries that didn't fully work, debugged it untill reaching the final code at the final block.


In [ ]:
from dataclasses import dataclass, field

@dataclass
class Ingredient:
    name = ""
    benefits = []
    recommended_percentage = 0
    max_percentage = 0

    def set_ingredient(self, name, benefits, recommended_percentage, max_percentage):
        self.name = name
        self.benefits = benefits
        self.recommended_percentage = recommended_percentage
        self.max_percentage = max_percentage

    def __repr__(self):
        return f"Ingredient(name={self.name}, benefits={self.benefits}, recommended_percentage={self.recommended_percentage}, max_percentage={self.max_percentage})"

@dataclass
class Product:
    name = ""
    product_type = ""
    ingredients = []
    total_percentage = 0

    def set_product(self, name, product_type):
        self.name = name
        self.product_type = product_type
        self.ingredients = []
        self.total_percentage = 0

    def add_ingredient(self, ingredient, percentage):
        if self.total_percentage + percentage <= 100:
            if percentage <= ingredient.max_percentage:
                self.ingredients.append((ingredient, percentage))
                self.total_percentage += percentage
            else:
                print(f"Error: Cannot add {ingredient.name} at {percentage}%. Max allowed is {ingredient.max_percentage}%.")
        else:
            print(f"Error: Total percentage exceeds 100%. Cannot add {ingredient.name}.")

    def calculate_benefit_score(self):
        benefit_score = 0
        for ingredient, percentage in self.ingredients:
            benefit_score += (percentage / 100) * ingredient.recommended_percentage
        return benefit_score

    def __repr__(self):
        return f"Product(name={self.name}, product_type={self.product_type}, ingredients={self.ingredients}, total_percentage={self.total_percentage})"

@dataclass
class User:
    name = ""
    age = 0
    gender = ""
    skin_type = ""
    skin_concerns = []
    recommended_products = []

    def set_user(self, name, age, gender, skin_type, skin_concerns):
        self.name = name
        self.age = age
        self.gender = gender
        self.skin_type = skin_type
        self.skin_concerns = skin_concerns
        self.recommended_products = []

    def __repr__(self):
        return f"User(name={self.name}, age={self.age}, gender={self.gender}, skin_type={self.skin_type}, skin_concerns={self.skin_concerns})"

# Test the classes
def test_classes():
    # Create some ingredients
    ingredient1 = Ingredient()
    ingredient1.set_ingredient("Aloe Vera", ["Soothing", "Hydration"], 5, 10)

    ingredient2 = Ingredient()
    ingredient2.set_ingredient("Salicylic Acid", ["Acne", "Exfoliation"], 2, 5)

    ingredient3 = Ingredient()
    ingredient3.set_ingredient("Hyaluronic Acid", ["Hydration", "Plumping"], 3, 10)

    # Print ingredient instances
    print(ingredient1)
    print(ingredient2)
    print(ingredient3)

    # Create a product and add ingredients to it
    product = Product()
    product.set_product("Hydrating Serum", "serum")
    product.add_ingredient(ingredient1, -5)
    product.add_ingredient(ingredient3, 3)

    # Print product instance
    print(product)

    # Create a user and assign some skin concerns
    user = User()
    user.set_user("Alice", 30, "female", "combination", ["acne", "hydration"])

    # Print user instance
    print(user)

# Run the test
test_classes()


Ingredient(name=Aloe Vera, benefits=['Soothing', 'Hydration'], recommended_percentage=5, max_percentage=10)
Ingredient(name=Salicylic Acid, benefits=['Acne', 'Exfoliation'], recommended_percentage=2, max_percentage=5)
Ingredient(name=Hyaluronic Acid, benefits=['Hydration', 'Plumping'], recommended_percentage=3, max_percentage=10)
Product(name=Hydrating Serum, product_type=serum, ingredients=[(Ingredient(name=Aloe Vera, benefits=['Soothing', 'Hydration'], recommended_percentage=5, max_percentage=10), -5), (Ingredient(name=Hyaluronic Acid, benefits=['Hydration', 'Plumping'], recommended_percentage=3, max_percentage=10), 3)], total_percentage=-2)
User(name=Alice, age=30, gender=female, skin_type=combination, skin_concerns=['acne', 'hydration'])


In [ ]:
@dataclass
class Ingredient:
    name = ""
    benefits = []
    recommended_percentage = 0
    max_percentage = 0

    def set_ingredient(self, name, benefits, recommended_percentage, max_percentage):
        self.name = name
        self.benefits = benefits
        self.recommended_percentage = recommended_percentage
        self.max_percentage = max_percentage

    def __repr__(self):
        return f"Ingredient(name={self.name}, benefits={self.benefits}, recommended_percentage={self.recommended_percentage}, max_percentage={self.max_percentage})"

@dataclass
class Product:
    name = ""
    product_type = ""
    ingredients = []
    total_percentage = 0

    def set_product(self, name, product_type):
        self.name = name
        self.product_type = product_type
        self.ingredients = []
        self.total_percentage = 0

    def add_ingredient(self, ingredient, percentage):
        if self.total_percentage + percentage <= 100:
            if percentage <= ingredient.max_percentage:
                self.ingredients.append((ingredient, percentage))
                self.total_percentage += percentage
            else:
                print(f"Error: Cannot add {ingredient.name} at {percentage}%. Max allowed is {ingredient.max_percentage}%.")
        else:
            print(f"Error: Total percentage exceeds 100%. Cannot add {ingredient.name}.")

    def calculate_benefit_score(self):
        benefit_score = 0
        for ingredient, percentage in self.ingredients:
            benefit_score += (percentage / 100) * ingredient.recommended_percentage
        return benefit_score

    def __repr__(self):
        return f"Product(name={self.name}, product_type={self.product_type}, ingredients={self.ingredients}, total_percentage={self.total_percentage})"

@dataclass
class User:
    name = ""
    age = 0
    gender = ""
    skin_type = ""
    skin_concerns = []
    recommended_products = []

    def set_user(self, name, age, gender, skin_type, skin_concerns):
        self.name = name
        self.age = age
        self.gender = gender
        self.skin_type = skin_type
        self.skin_concerns = skin_concerns
        self.recommended_products = []

    def __repr__(self):
        return f"User(name={self.name}, age={self.age}, gender={self.gender}, skin_type={self.skin_type}, skin_concerns={self.skin_concerns})"

# Dictionary to store users
users_dict = {}

def add_new_user():
    name = input("Enter your name: ")
    age = int(input("Enter your age: "))
    gender = input("Enter your gender: ")
    skin_type = input("Enter your skin type (e.g., oily, dry, combination): ")
    skin_concerns = input("Enter your skin concerns (comma separated, e.g., acne, hydration): ").split(", ")

    user = User()
    user.set_user(name, age, gender, skin_type, skin_concerns)
    users_dict[name] = user

    print(f"User {name} added successfully.")
    print(user)

# Function to print all users
def print_all_users():
    for name, user in users_dict.items():
        print(user)

# Test the add_new_user function
add_new_user()
print_all_users()


Enter your name: ortal
Enter your age: 38
Enter your gender: female
Enter your skin type (e.g., oily, dry, combination): oily
Enter your skin concerns (comma separated, e.g., acne, hydration): acne
User ortal added successfully.
User(name=ortal, age=38, gender=female, skin_type=oily, skin_concerns=['acne'])
User(name=ortal, age=38, gender=female, skin_type=oily, skin_concerns=['acne'])


In [ ]:
@dataclass
class Ingredient:
    name = ""
    benefits = []
    recommended_percentage = 0
    max_percentage = 0

    def set_ingredient(self, name, benefits, recommended_percentage, max_percentage):
        self.name = name
        self.benefits = benefits
        self.recommended_percentage = recommended_percentage
        self.max_percentage = max_percentage

    def __repr__(self):
        return f"Ingredient(name={self.name}, benefits={self.benefits}, recommended_percentage={self.recommended_percentage}, max_percentage={self.max_percentage})"

@dataclass
class Product:
    name = ""
    product_type = ""
    ingredients = []
    total_percentage = 0

    def set_product(self, name, product_type):
        self.name = name
        self.product_type = product_type
        self.ingredients = []
        self.total_percentage = 0

    def add_ingredient(self, ingredient, percentage):
        if self.total_percentage + percentage <= 100:
            if percentage <= ingredient.max_percentage:
                self.ingredients.append((ingredient, percentage))
                self.total_percentage += percentage
            else:
                print(f"Error: Cannot add {ingredient.name} at {percentage}%. Max allowed is {ingredient.max_percentage}%.")
        else:
            print(f"Error: Total percentage exceeds 100%. Cannot add {ingredient.name}.")

    def calculate_benefit_score(self):
        benefit_score = 0
        for ingredient, percentage in self.ingredients:
            benefit_score += (percentage / 100) * ingredient.recommended_percentage
        return benefit_score

    def __repr__(self):
        return f"Product(name={self.name}, product_type={self.product_type}, ingredients={self.ingredients}, total_percentage={self.total_percentage})"

@dataclass
class User:
    name = ""
    age = 0
    gender = ""
    skin_type = ""
    skin_concerns = []
    recommended_products = []

    def set_user(self, name, age, gender, skin_type, skin_concerns):
        self.name = name
        self.age = age
        self.gender = gender
        self.skin_type = skin_type
        self.skin_concerns = skin_concerns
        self.recommended_products = []

    def __repr__(self):
        return f"User(name={self.name}, age={self.age}, gender={self.gender}, skin_type={self.skin_type}, skin_concerns={self.skin_concerns})"

# Dictionary to store users
users_dict = {}

def add_new_user():
    name = input("Enter your name: ")
    age = int(input("Enter your age: "))
    gender = input("Enter your gender: ")
    skin_type = input("Enter your skin type (e.g., oily, dry, combination): ")
    skin_concerns = input("Enter your skin concerns (comma separated, e.g., acne, hydration): ").split(", ")

    user = User()
    user.set_user(name, age, gender, skin_type, skin_concerns)
    users_dict[name] = user

    print(f"User {name} added successfully.")
    print(user)

def print_all_users():
    print("All Users:")
    for name, user in users_dict.items():
        print(f"{name}: {user}")

# Test the add_new_user function
add_new_user()
print_all_users()


Enter your name: rona
Enter your age: 1
Enter your gender: female
Enter your skin type (e.g., oily, dry, combination): dry
Enter your skin concerns (comma separated, e.g., acne, hydration): hydration
User rona added successfully.
User(name=rona, age=1, gender=female, skin_type=dry, skin_concerns=['hydration'])
All Users:
rona: User(name=rona, age=1, gender=female, skin_type=dry, skin_concerns=['hydration'])


In [ ]:
class Ingredient:
    def __init__(self, name, benefits, recommended_percentage, max_percentage):
        self.name = name
        self.benefits = benefits
        self.recommended_percentage = recommended_percentage
        self.max_percentage = max_percentage

    def __repr__(self):
        return f"Ingredient(name={self.name}, benefits={self.benefits}, recommended_percentage={self.recommended_percentage}, max_percentage={self.max_percentage})"

class Product:
    def __init__(self, name, product_type):
        self.name = name
        self.product_type = product_type
        self.ingredients = []
        self.total_percentage = 0

    def add_ingredient(self, ingredient, percentage):
        if self.total_percentage + percentage <= 100:
            if percentage <= ingredient.max_percentage:
                self.ingredients.append((ingredient, percentage))
                self.total_percentage += percentage
            else:
                print(f"Error: Cannot add {ingredient.name} at {percentage}%. Max allowed is {ingredient.max_percentage}%.")
        else:
            print(f"Error: Total percentage exceeds 100%. Cannot add {ingredient.name}.")

    def calculate_benefit_score(self):
        benefit_score = 0
        for ingredient, percentage in self.ingredients:
            benefit_score += (percentage / 100) * ingredient.recommended_percentage
        return benefit_score

    def __repr__(self):
        return f"Product(name={self.name}, product_type={self.product_type}, ingredients={self.ingredients}, total_percentage={self.total_percentage})"

class User:
    def __init__(self, name, age, gender, skin_type, skin_concerns):
        self.name = name
        self.age = age
        self.gender = gender
        self.skin_type = skin_type
        self.skin_concerns = skin_concerns
        self.recommended_products = []

    def __repr__(self):
        return f"User(name={self.name}, age={self.age}, gender={self.gender}, skin_type={self.skin_type}, skin_concerns={self.skin_concerns})"

# Dictionary to store users
users_dict = {}

def add_new_user():
    name = input("Enter your name: ")
    age = int(input("Enter your age: "))
    gender = input("Enter your gender: ")
    skin_type = input("Enter your skin type (e.g., oily, dry, combination): ")
    skin_concerns = input("Enter your skin concerns (comma separated, e.g., acne, hydration): ").split(", ")

    user = User(name, age, gender, skin_type, skin_concerns)
    users_dict[name] = user

    print(f"User {name} added successfully.")

def print_all_users():
    print("All Users:")
    for name, user in users_dict.items():
        print(f"{name}: {user}")

# Test the add_new_user function
add_new_user()
print_all_users()


Enter your name: rona
Enter your age: 1
Enter your gender: female
Enter your skin type (e.g., oily, dry, combination): dry
Enter your skin concerns (comma separated, e.g., acne, hydration): hydration
User rona added successfully.
All Users:
rona: User(name=rona, age=1, gender=female, skin_type=dry, skin_concerns=['hydration'])


In [ ]:
class Ingredient:
    def __init__(self, name, benefits, recommended_percentage, max_percentage):
        self.name = name
        self.benefits = benefits
        self.recommended_percentage = recommended_percentage
        self.max_percentage = max_percentage

    def __repr__(self):
        return f"Ingredient(name={self.name}, benefits={self.benefits}, recommended_percentage={self.recommended_percentage}, max_percentage={self.max_percentage})"

class Product:
    def __init__(self, name, product_type):
        self.name = name
        self.product_type = product_type
        self.ingredients = []
        self.total_percentage = 0

    def add_ingredient(self, ingredient, percentage):
        if self.total_percentage + percentage <= 100:
            if percentage <= ingredient.max_percentage:
                self.ingredients.append((ingredient, percentage))
                self.total_percentage += percentage
            else:
                print(f"Error: Cannot add {ingredient.name} at {percentage}%. Max allowed is {ingredient.max_percentage}%.")
        else:
            print(f"Error: Total percentage exceeds 100%. Cannot add {ingredient.name}.")

    def calculate_benefit_score(self):
        benefit_score = 0
        for ingredient, percentage in self.ingredients:
            benefit_score += (percentage / 100) * ingredient.recommended_percentage
        return benefit_score

    def __repr__(self):
        return f"Product(name={self.name}, product_type={self.product_type}, ingredients={self.ingredients}, total_percentage={self.total_percentage})"

class User:
    def __init__(self, name, age, gender, skin_type, skin_concerns):
        self.name = name
        self.age = age
        self.gender = gender
        self.skin_type = skin_type
        self.skin_concerns = skin_concerns
        self.recommended_products = []

    def __repr__(self):
        return f"User(name={self.name}, age={self.age}, gender={self.gender}, skin_type={self.skin_type}, skin_concerns={self.skin_concerns})"

# Dictionary to store users
users_dict = {}

def add_new_user():
    name = input("Enter your name: ")
    age = int(input("Enter your age: "))
    gender = input("Enter your gender: ")
    skin_type = input("Enter your skin type (e.g., oily, dry, combination): ")
    skin_concerns = input("Enter your skin concerns (comma separated, e.g., acne, hydration): ").split(", ")

    user = User(name, age, gender, skin_type, skin_concerns)
    users_dict[name] = user

    print(f"User {name} added successfully.")

def print_all_users():
    print("All Users:")
    for name, user in users_dict.items():
        print(f"{name}: {user}")

# Function to continuously add users and print the dictionary
def run_program():
    while True:
        add_new_user()
        print_all_users()
        cont = input("Do you want to add another user? (yes/no): ").strip().lower()
        if cont != 'yes':
            break

# Run the program
run_program()


Enter your name: ortla
Enter your age: 38
Enter your gender: female
Enter your skin type (e.g., oily, dry, combination): oily
Enter your skin concerns (comma separated, e.g., acne, hydration): acne
User ortla added successfully.
All Users:
ortla: User(name=ortla, age=38, gender=female, skin_type=oily, skin_concerns=['acne'])
Do you want to add another user? (yes/no): yes
Enter your name: rona
Enter your age: 1
Enter your gender: female
Enter your skin type (e.g., oily, dry, combination): dry
Enter your skin concerns (comma separated, e.g., acne, hydration): hydration
User rona added successfully.
All Users:
ortla: User(name=ortla, age=38, gender=female, skin_type=oily, skin_concerns=['acne'])
rona: User(name=rona, age=1, gender=female, skin_type=dry, skin_concerns=['hydration'])
Do you want to add another user? (yes/no): no


In [ ]:
class Ingredient:
    def __init__(self, name, benefits, recommended_percentage, max_percentage):
        self.name = name
        self.benefits = benefits
        self.recommended_percentage = recommended_percentage
        self.max_percentage = max_percentage

    def __repr__(self):
        return f"Ingredient(name={self.name}, benefits={self.benefits}, recommended_percentage={self.recommended_percentage}, max_percentage={self.max_percentage})"

class Product:
    def __init__(self, name, product_type):
        self.name = name
        self.product_type = product_type
        self.ingredients = []
        self.total_percentage = 0

    def add_ingredient(self, ingredient, percentage):
        if self.total_percentage + percentage <= 100:
            if percentage <= ingredient.max_percentage:
                self.ingredients.append((ingredient, percentage))
                self.total_percentage += percentage
            else:
                print(f"Error: Cannot add {ingredient.name} at {percentage}%. Max allowed is {ingredient.max_percentage}%.")
        else:
            print(f"Error: Total percentage exceeds 100%. Cannot add {ingredient.name}.")

    def calculate_benefit_score(self):
        benefit_score = 0
        for ingredient, percentage in self.ingredients:
            benefit_score += (percentage / 100) * ingredient.recommended_percentage
        return benefit_score

    def __repr__(self):
        return f"Product(name={self.name}, product_type={self.product_type}, ingredients={self.ingredients}, total_percentage={self.total_percentage})"

class User:
    def __init__(self, name, age, gender, skin_type, skin_concerns):
        self.name = name
        self.age = age
        self.gender = gender
        self.skin_type = skin_type
        self.skin_concerns = skin_concerns
        self.recommended_products = []

    def __repr__(self):
        return f"User(name={self.name}, age={self.age}, gender={self.gender}, skin_type={self.skin_type}, skin_concerns={self.skin_concerns})"

# Dictionary to store users
users_dict = {}

def add_new_user():
    name = input("Enter your name: ")
    age = int(input("Enter your age: "))
    gender = input("Enter your gender: ")
    skin_type = input("Enter your skin type (e.g., oily, dry, combination): ")
    skin_concerns = input("Enter your skin concerns (comma separated, e.g., acne, hydration): ").split(", ")

    user = User(name, age, gender, skin_type, skin_concerns)
    users_dict[name] = user

    print(f"User {name} added successfully.")

def print_all_users():
    print("All Users Dictionary:")
    print(users_dict)

# Function to continuously add users and print the dictionary
def run_program():
    while True:
        add_new_user()
        print_all_users()
        cont = input("Do you want to add another user? (yes/no): ").strip().lower()
        if cont != 'yes':
            break

# Run the program
run_program()


Enter your name: ortla
Enter your age: 38
Enter your gender: female
Enter your skin type (e.g., oily, dry, combination): oily
Enter your skin concerns (comma separated, e.g., acne, hydration): acne
User ortla added successfully.
All Users Dictionary:
{'ortla': User(name=ortla, age=38, gender=female, skin_type=oily, skin_concerns=['acne'])}
Do you want to add another user? (yes/no): yes
Enter your name: rona
Enter your age: 1
Enter your gender: female
Enter your skin type (e.g., oily, dry, combination): dry
Enter your skin concerns (comma separated, e.g., acne, hydration): hydration
User rona added successfully.
All Users Dictionary:
{'ortla': User(name=ortla, age=38, gender=female, skin_type=oily, skin_concerns=['acne']), 'rona': User(name=rona, age=1, gender=female, skin_type=dry, skin_concerns=['hydration'])}
Do you want to add another user? (yes/no): no


In [ ]:
class Ingredient:
    def __init__(self, name, benefits, recommended_percentage, max_percentage):
        self.name = name
        self.benefits = benefits
        self.recommended_percentage = recommended_percentage
        self.max_percentage = max_percentage

    def __repr__(self):
        return f"Ingredient(name={self.name}, benefits={self.benefits}, recommended_percentage={self.recommended_percentage}, max_percentage={self.max_percentage})"

class Product:
    def __init__(self, name, product_type):
        self.name = name
        self.product_type = product_type
        self.ingredients = []
        self.total_percentage = 0

    def add_ingredient(self, ingredient, percentage):
        if self.total_percentage + percentage <= 100:
            if percentage <= ingredient.max_percentage:
                self.ingredients.append((ingredient, percentage))
                self.total_percentage += percentage
            else:
                print(f"Error: Cannot add {ingredient.name} at {percentage}%. Max allowed is {ingredient.max_percentage}%.")
        else:
            print(f"Error: Total percentage exceeds 100%. Cannot add {ingredient.name}.")

    def calculate_benefit_score(self):
        benefit_score = 0
        for ingredient, percentage in self.ingredients:
            benefit_score += (percentage / 100) * ingredient.recommended_percentage
        return benefit_score

    def __repr__(self):
        return f"Product(name={self.name}, product_type={self.product_type}, ingredients={self.ingredients}, total_percentage={self.total_percentage})"

class User:
    def __init__(self, name, age, gender, skin_type, skin_concerns):
        self.name = name
        self.age = age
        self.gender = gender
        self.skin_type = skin_type
        self.skin_concerns = skin_concerns
        self.recommended_products = []

    def __repr__(self):
        return f"User(name={self.name}, age={self.age}, gender={self.gender}, skin_type={self.skin_type}, skin_concerns={self.skin_concerns})"

# Dictionaries to store users and products
users_dict = {}
products_dict = {}

def add_new_user():
    name = input("Enter your name: ")
    age = int(input("Enter your age: "))
    gender = input("Enter your gender: ")
    skin_type = input("Enter your skin type (e.g., oily, dry, combination): ")
    skin_concerns = input("Enter your skin concerns (comma separated, e.g., acne, hydration): ").split(", ")

    user = User(name, age, gender, skin_type, skin_concerns)
    users_dict[name] = user

    print(f"User {name} added successfully.")

def add_new_product():
    product_name = input("Enter the product name: ")
    product_type = input("Enter the product type: ")
    product = Product(product_name, product_type)

    while True:
        ingredient_name = input("Enter the ingredient name: ")
        benefits = input("Enter the benefits of the ingredient (comma separated): ").split(", ")
        recommended_percentage = float(input("Enter the recommended percentage of the ingredient: "))
        max_percentage = float(input("Enter the max percentage of the ingredient: "))

        ingredient = Ingredient(ingredient_name, benefits, recommended_percentage, max_percentage)
        percentage = float(input(f"Enter the percentage of {ingredient_name} in the product: "))
        product.add_ingredient(ingredient, percentage)

        more_ingredients = input("Do you want to add another ingredient? (yes/no): ").strip().lower()
        if more_ingredients != 'yes':
            break

    products_dict[product_name] = product
    print(f"Product {product_name} added successfully.")

def print_all_users():
    print("All Users Dictionary:")
    print(users_dict)

def print_all_products():
    print("All Products Dictionary:")
    print(products_dict)

# Function to continuously add users and products, and print the dictionaries
def run_program():
    while True:
        choice = input("Do you want to add a user or a product? (user/product): ").strip().lower()
        if choice == 'user':
            add_new_user()
            print_all_users()
        elif choice == 'product':
            add_new_product()
            print_all_products()
        else:
            print("Invalid choice. Please enter 'user' or 'product'.")

        cont = input("Do you want to continue? (yes/no): ").strip().lower()
        if cont != 'yes':
            break

# Run the program
run_program()


Do you want to add a user or a product? (user/product): product
Enter the product name: aloe
Enter the product type: cream
Enter the ingredient name: aloevera
Enter the benefits of the ingredient (comma separated): dry
Enter the recommended percentage of the ingredient: 50
Enter the max percentage of the ingredient: 100
Enter the percentage of aloevera in the product: 53
Do you want to add another ingredient? (yes/no): yes
Enter the ingredient name: ampula for hair
Enter the benefits of the ingredient (comma separated): hydration
Enter the recommended percentage of the ingredient: 20
Enter the max percentage of the ingredient: 80
Enter the percentage of ampula for hair in the product: 40
Do you want to add another ingredient? (yes/no): no
Product aloe added successfully.
All Products Dictionary:
{'aloe': Product(name=aloe, product_type=cream, ingredients=[(Ingredient(name=aloevera, benefits=['dry'], recommended_percentage=50.0, max_percentage=100.0), 53.0), (Ingredient(name=ampula for 

In [ ]:
class Ingredient:
    def __init__(self, name, benefits, recommended_percentage, max_percentage):
        self.name = name
        self.benefits = benefits
        self.recommended_percentage = recommended_percentage
        self.max_percentage = max_percentage

    def __repr__(self):
        return f"Ingredient(name={self.name}, benefits={self.benefits}, recommended_percentage={self.recommended_percentage}, max_percentage={self.max_percentage})"

class Product:
    def __init__(self, name, product_type):
        self.name = name
        self.product_type = product_type
        self.ingredients = []
        self.total_percentage = 0

    def add_ingredient(self, ingredient, percentage):
        if self.total_percentage + percentage <= 100:
            if percentage <= ingredient.max_percentage:
                self.ingredients.append((ingredient, percentage))
                self.total_percentage += percentage
            else:
                print(f"Error: Cannot add {ingredient.name} at {percentage}%. Max allowed is {ingredient.max_percentage}%.")
        else:
            print(f"Error: Total percentage exceeds 100%. Cannot add {ingredient.name}.")

    def calculate_benefit_score(self):
        benefit_score = 0
        for ingredient, percentage in self.ingredients:
            benefit_score += (percentage / 100) * ingredient.recommended_percentage
        return benefit_score

    def __repr__(self):
        return f"Product(name={self.name}, product_type={self.product_type}, ingredients={self.ingredients}, total_percentage={self.total_percentage})"

class User:
    def __init__(self, name, age, gender, skin_type, skin_concerns):
        self.name = name
        self.age = age
        self.gender = gender
        self.skin_type = skin_type
        self.skin_concerns = skin_concerns
        self.recommended_products = []

    def __repr__(self):
        return f"User(name={self.name}, age={self.age}, gender={self.gender}, skin_type={self.skin_type}, skin_concerns={self.skin_concerns})"

# Dictionaries to store users and products
users_dict = {}
products_dict = {}

def add_new_user():
    name = input("Enter your name: ")
    age = int(input("Enter your age: "))
    gender = input("Enter your gender: ")
    skin_type = input("Enter your skin type (e.g., oily, dry, combination): ")
    skin_concerns = input("Enter your skin concerns (comma separated, e.g., acne, hydration): ").split(", ")

    user = User(name, age, gender, skin_type, skin_concerns)
    users_dict[name] = user

    print(f"User {name} added successfully.")

def add_new_product():
    product_name = input("Enter the product name: ")
    product_type = input("Enter the product type: ")
    product = Product(product_name, product_type)

    while True:
        ingredient_name = input("Enter the ingredient name: ")
        benefits = input("Enter the benefits of the ingredient (comma separated): ").split(", ")
        recommended_percentage = float(input("Enter the recommended percentage of the ingredient: "))
        max_percentage = float(input("Enter the max percentage of the ingredient: "))

        ingredient = Ingredient(ingredient_name, benefits, recommended_percentage, max_percentage)
        percentage = float(input(f"Enter the percentage of {ingredient_name} in the product: "))
        product.add_ingredient(ingredient, percentage)

        more_ingredients = input("Do you want to add another ingredient? (yes/no): ").strip().lower()
        if more_ingredients != 'yes':
            break

    products_dict[product_name] = product
    print(f"Product {product_name} added successfully.")

def print_all_users():
    print("All Users Dictionary:")
    for name, user in users_dict.items():
        print(f"{name}: {user}")

def print_all_products():
    print("All Products Dictionary:")
    for name, product in products_dict.items():
        print(f"{name}: {product}")

def recommend_products_to_users():
    for user_name, user in users_dict.items():
        recommended_products = []
        for product_name, product in products_dict.items():
            if any(concern in product_name.lower() for concern in user.skin_concerns):
                recommended_products.append(product)
        user.recommended_products = recommended_products

def run_program():
    while True:
        choice = input("Do you want to add a user or a product? (user/product): ").strip().lower()
        if choice == 'user':
            add_new_user()
            print_all_users()
        elif choice == 'product':
            add_new_product()
            print_all_products()
        else:
            print("Invalid choice. Please enter 'user' or 'product'.")

        cont = input("Do you want to continue? (yes/no): ").strip().lower()
        if cont != 'yes':
            break

    recommend_products_to_users()

    # Print recommended products for each user
    print("\nRecommended Products for Users:")
    for user_name, user in users_dict.items():
        print(f"{user_name}:")
        if user.recommended_products:
            for product in user.recommended_products:
                print(f"   {product.name}")
        else:
            print("   No recommended products")

# Run the program
run_program()


Do you want to add a user or a product? (user/product): user
Enter your name: ortal
Enter your age: 38
Enter your gender: female
Enter your skin type (e.g., oily, dry, combination): oily
Enter your skin concerns (comma separated, e.g., acne, hydration): acne
User ortal added successfully.
All Users Dictionary:
ortal: User(name=ortal, age=38, gender=female, skin_type=oily, skin_concerns=['acne'])
Do you want to continue? (yes/no): yes
Do you want to add a user or a product? (user/product): user
Enter your name: rona
Enter your age: 1
Enter your gender: female
Enter your skin type (e.g., oily, dry, combination): dry
Enter your skin concerns (comma separated, e.g., acne, hydration): hydration
User rona added successfully.
All Users Dictionary:
ortal: User(name=ortal, age=38, gender=female, skin_type=oily, skin_concerns=['acne'])
rona: User(name=rona, age=1, gender=female, skin_type=dry, skin_concerns=['hydration'])
Do you want to continue? (yes/no): yes
Do you want to add a user or a prod

KeyboardInterrupt: Interrupted by user

In [ ]:
class Ingredient:
    def __init__(self, name, benefits, recommended_percentage, max_percentage):
        self.name = name
        self.benefits = benefits
        self.recommended_percentage = recommended_percentage
        self.max_percentage = max_percentage

    def __repr__(self):
        return f"Ingredient(name={self.name}, benefits={self.benefits}, recommended_percentage={self.recommended_percentage}, max_percentage={self.max_percentage})"

class Product:
    def __init__(self, name, product_type):
        self.name = name
        self.product_type = product_type
        self.ingredients = []
        self.total_percentage = 0

    def add_ingredient(self, ingredient, percentage):
        if self.total_percentage + percentage <= 100:
            if percentage <= ingredient.max_percentage:
                self.ingredients.append((ingredient, percentage))
                self.total_percentage += percentage
            else:
                print(f"Error: Cannot add {ingredient.name} at {percentage}%. Max allowed is {ingredient.max_percentage}%.")
        else:
            print(f"Error: Total percentage exceeds 100%. Cannot add {ingredient.name}.")

    def calculate_benefit_score(self):
        benefit_score = 0
        for ingredient, percentage in self.ingredients:
            benefit_score += (percentage / 100) * ingredient.recommended_percentage
        return benefit_score

    def __repr__(self):
        return f"Product(name={self.name}, product_type={self.product_type}, ingredients={self.ingredients}, total_percentage={self.total_percentage})"

class User:
    def __init__(self, name, age, gender, skin_type, skin_concerns):
        self.name = name
        self.age = age
        self.gender = gender
        self.skin_type = skin_type
        self.skin_concerns = skin_concerns
        self.recommended_products = []

    def __repr__(self):
        return f"User(name={self.name}, age={self.age}, gender={self.gender}, skin_type={self.skin_type}, skin_concerns={self.skin_concerns})"

# Dictionaries to store users and products
users_dict = {}
products_dict = {}

def add_new_user():
    name = input("Enter your name: ")
    age = int(input("Enter your age: "))
    gender = input("Enter your gender: ")
    skin_type = input("Enter your skin type (e.g., oily, dry, combination): ")
    skin_concerns = input("Enter your skin concerns (comma separated, e.g., acne, hydration): ").split(", ")

    user = User(name, age, gender, skin_type, skin_concerns)
    users_dict[name] = user

    print(f"User {name} added successfully.")

def add_new_product():
    product_name = input("Enter the product name: ")
    product_type = input("Enter the product type: ")
    product = Product(product_name, product_type)

    while True:
        ingredient_name = input("Enter the ingredient name: ")
        benefits = input("Enter the benefits of the ingredient (comma separated): ").split(", ")
        recommended_percentage = float(input("Enter the recommended percentage of the ingredient: "))
        max_percentage = float(input("Enter the max percentage of the ingredient: "))

        ingredient = Ingredient(ingredient_name, benefits, recommended_percentage, max_percentage)
        percentage = float(input(f"Enter the percentage of {ingredient_name} in the product: "))
        product.add_ingredient(ingredient, percentage)

        more_ingredients = input("Do you want to add another ingredient? (yes/no): ").strip().lower()
        if more_ingredients != 'yes':
            break

    products_dict[product_name] = product
    print(f"Product {product_name} added successfully.")

def print_all_users():
    print("All Users Dictionary:")
    for name, user in users_dict.items():
        print(f"{name}: {user}")

def print_all_products():
    print("All Products Dictionary:")
    for name, product in products_dict.items():
        print(f"{name}: {product}")

def recommend_products_to_users():
    for user_name, user in users_dict.items():
        recommended_products = []
        for product_name, product in products_dict.items():
            if any(concern in product_name.lower() for concern in user.skin_concerns):
                recommended_products.append(product)
        user.recommended_products = recommended_products

def run_program():
    while True:
        choice = input("Do you want to add a user or a product? (user/product): ").strip().lower()
        if choice == 'user':
            add_new_user()
            print_all_users()
        elif choice == 'product':
            add_new_product()
            print_all_products()
        else:
            print("Invalid choice. Please enter 'user' or 'product'.")

        cont = input("Do you want to continue? (yes/no): ").strip().lower()
        if cont != 'yes':
            break

    recommend_products_to_users()

    # Print recommended products for each user
    print("\nRecommended Products for Users:")
    for user_name, user in users_dict.items():
        print(f"{user_name}:")
        if user.recommended_products:
            for product in user.recommended_products:
                print(f"   {product.name}")
        else:
            print("   No recommended products")

# Run the program
run_program()


User ortal added successfully.
All Users Dictionary:
ortal: User(name=ortal, age=38, gender=female, skin_type=oily, skin_concerns=['acne'])
Product aloe added successfully.
All Products Dictionary:
aloe: Product(name=aloe, product_type=alovera, ingredients=[(Ingredient(name=alovera, benefits=['acne'], recommended_percentage=80.0, max_percentage=90.0), 85.0)], total_percentage=85.0)


KeyboardInterrupt: Interrupted by user

In [ ]:
class Ingredient:
    def __init__(self, name, benefits, recommended_percentage, max_percentage):
        self.name = name
        self.benefits = benefits
        self.recommended_percentage = recommended_percentage
        self.max_percentage = max_percentage

    def __repr__(self):
        return f"Ingredient(name={self.name}, benefits={self.benefits}, recommended_percentage={self.recommended_percentage}, max_percentage={self.max_percentage})"

class Product:
    def __init__(self, name, product_type):
        self.name = name
        self.product_type = product_type
        self.ingredients = []
        self.total_percentage = 0

    def add_ingredient(self, ingredient, percentage):
        if self.total_percentage + percentage <= 100:
            if percentage <= ingredient.max_percentage:
                self.ingredients.append((ingredient, percentage))
                self.total_percentage += percentage
            else:
                print(f"Error: Cannot add {ingredient.name} at {percentage}%. Max allowed is {ingredient.max_percentage}%.")
        else:
            print(f"Error: Total percentage exceeds 100%. Cannot add {ingredient.name}.")

    def calculate_benefit_score(self):
        benefit_score = 0
        for ingredient, percentage in self.ingredients:
            benefit_score += (percentage / 100) * ingredient.recommended_percentage
        return benefit_score

    def __repr__(self):
        return f"Product(name={self.name}, product_type={self.product_type}, ingredients={self.ingredients}, total_percentage={self.total_percentage})"

class User:
    def __init__(self, name, age, gender, skin_type, skin_concerns):
        self.name = name
        self.age = age
        self.gender = gender
        self.skin_type = skin_type
        self.skin_concerns = skin_concerns
        self.recommended_products = []

    def __repr__(self):
        return f"User(name={self.name}, age={self.age}, gender={self.gender}, skin_type={self.skin_type}, skin_concerns={self.skin_concerns})"

# Dictionaries to store users and products
users_dict = {}
products_dict = {}

def add_new_user():
    name = input("Enter your name: ")
    age = int(input("Enter your age: "))
    gender = input("Enter your gender: ")
    skin_type = input("Enter your skin type (e.g., oily, dry, combination): ")
    skin_concerns = input("Enter your skin concerns (comma separated, e.g., acne, hydration): ").split(", ")

    user = User(name, age, gender, skin_type, skin_concerns)
    users_dict[name] = user

    print(f"User {name} added successfully.")

def add_new_product():
    product_name = input("Enter the product name: ")
    product_type = input("Enter the product type: ")
    product = Product(product_name, product_type)

    while True:
        ingredient_name = input("Enter the ingredient name: ")
        benefits = input("Enter the benefits of the ingredient (comma separated): ").split(", ")
        recommended_percentage = float(input("Enter the recommended percentage of the ingredient: "))
        max_percentage = float(input("Enter the max percentage of the ingredient: "))

        ingredient = Ingredient(ingredient_name, benefits, recommended_percentage, max_percentage)
        percentage = float(input(f"Enter the percentage of {ingredient_name} in the product: "))
        product.add_ingredient(ingredient, percentage)

        more_ingredients = input("Do you want to add another ingredient? (yes/no): ").strip().lower()
        if more_ingredients != 'yes':
            break

    products_dict[product_name] = product
    print(f"Product {product_name} added successfully.")

def print_all_users():
    print("All Users Dictionary:")
    for name, user in users_dict.items():
        print(f"{name}: {user}")

def print_all_products():
    print("All Products Dictionary:")
    for name, product in products_dict.items():
        print(f"{name}: {product}")

def recommend_products_to_users():
    for user_name, user in users_dict.items():
        recommended_products = []
        for product_name, product in products_dict.items():
            for ingredient, _ in product.ingredients:
                if any(concern in ingredient.benefits for concern in user.skin_concerns):
                    recommended_products.append((product_name, ingredient))
                    break  # Stop searching further ingredients once a match is found
        user.recommended_products = recommended_products

def run_program():
    while True:
        choice = input("Do you want to add a user or a product? (user/product): ").strip().lower()
        if choice == 'user':
            add_new_user()
            print_all_users()
        elif choice == 'product':
            add_new_product()
            print_all_products()
        else:
            print("Invalid choice. Please enter 'user' or 'product'.")

        cont = input("Do you want to continue? (yes/no): ").strip().lower()
        if cont != 'yes':
            break

    recommend_products_to_users()

    # Ask user if they want to see recommended products and their ingredients
    for user_name, user in users_dict.items():
        show_products = input(f"\n{user_name}, do you want to see products and their fitting ingredients? (yes/no): ").strip().lower()
        if show_products == 'yes':
            print(f"\nProducts and their fitting ingredients for {user_name}:")
            for product_name, ingredient in user.recommended_products:
                print(f"   {product_name}: {ingredient.name}")
        else:
            print(f"\n{user_name} chose not to see products and their fitting ingredients.")

# Run the program
run_program()


Do you want to add a user or a product? (user/product): user
Enter your name: ortal
Enter your age: 38
Enter your gender: female
Enter your skin type (e.g., oily, dry, combination): oily
Enter your skin concerns (comma separated, e.g., acne, hydration): acne
User ortal added successfully.
All Users Dictionary:
ortal: User(name=ortal, age=38, gender=female, skin_type=oily, skin_concerns=['acne'])
Do you want to continue? (yes/no): yes
Do you want to add a user or a product? (user/product): product
Enter the product name: aloe
Enter the product type: cream
Enter the ingredient name: alovera
Enter the benefits of the ingredient (comma separated): acne
Enter the recommended percentage of the ingredient: 50
Enter the max percentage of the ingredient: 100
Enter the percentage of alovera in the product: 53
Do you want to add another ingredient? (yes/no): no
Product aloe added successfully.
All Products Dictionary:
aloe: Product(name=aloe, product_type=cream, ingredients=[(Ingredient(name=alov

KeyboardInterrupt: Interrupted by user

In [ ]:
class Ingredient:
    def __init__(self, name, benefits, recommended_percentage, max_percentage):
        self.name = name
        self.benefits = benefits
        self.recommended_percentage = recommended_percentage
        self.max_percentage = max_percentage

    def __repr__(self):
        return f"Ingredient(name={self.name}, benefits={self.benefits}, recommended_percentage={self.recommended_percentage}, max_percentage={self.max_percentage})"

class Product:
    def __init__(self, name, product_type):
        self.name = name
        self.product_type = product_type
        self.ingredient = None  # Only one ingredient per product
        self.total_percentage = 0

    def add_ingredient(self, ingredient, percentage):
        if self.total_percentage + percentage <= 100:
            if percentage <= ingredient.max_percentage:
                self.ingredient = ingredient
                self.total_percentage += percentage
            else:
                print(f"Error: Cannot add {ingredient.name} at {percentage}%. Max allowed is {ingredient.max_percentage}%.")
        else:
            print(f"Error: Total percentage exceeds 100%. Cannot add {ingredient.name}.")

    def calculate_benefit_score(self):
        if self.ingredient is not None:
            return self.ingredient.recommended_percentage
        else:
            return 0

    def __repr__(self):
        return f"Product(name={self.name}, product_type={self.product_type}, ingredient={self.ingredient}, total_percentage={self.total_percentage})"

class User:
    def __init__(self, name, age, gender, skin_type, skin_concerns):
        self.name = name
        self.age = age
        self.gender = gender
        self.skin_type = skin_type
        self.skin_concerns = skin_concerns
        self.recommended_product = None

    def __repr__(self):
        return f"User(name={self.name}, age={self.age}, gender={self.gender}, skin_type={self.skin_type}, skin_concerns={self.skin_concerns})"

# Dictionaries to store users and products
users_dict = {}
products_dict = {}

def add_new_user():
    name = input("Enter your name: ")
    age = int(input("Enter your age: "))
    gender = input("Enter your gender: ")
    skin_type = input("Enter your skin type (e.g., oily, dry, combination): ")
    skin_concerns = input("Enter your skin concerns (comma separated, e.g., acne, hydration): ").split(", ")

    user = User(name, age, gender, skin_type, skin_concerns)
    users_dict[name] = user

    print(f"User {name} added successfully.")

def add_new_product():
    product_name = input("Enter the product name: ")
    product_type = input("Enter the product type: ")
    product = Product(product_name, product_type)

    ingredient_name = input("Enter the ingredient name: ")
    benefits = input("Enter the benefits of the ingredient (comma separated): ").split(", ")
    recommended_percentage = float(input("Enter the recommended percentage of the ingredient: "))
    max_percentage = float(input("Enter the max percentage of the ingredient: "))

    ingredient = Ingredient(ingredient_name, benefits, recommended_percentage, max_percentage)
    percentage = float(input(f"Enter the percentage of {ingredient_name} in the product: "))
    product.add_ingredient(ingredient, percentage)

    products_dict[product_name] = product
    print(f"Product {product_name} added successfully.")

def print_all_users():
    print("All Users Dictionary:")
    for name, user in users_dict.items():
        print(f"{name}: {user}")

def print_all_products():
    print("All Products Dictionary:")
    for name, product in products_dict.items():
        print(f"{name}: {product}")

def recommend_products_to_users():
    for user_name, user in users_dict.items():
        recommended_product = None
        for product_name, product in products_dict.items():
            if product.ingredient is not None and any(concern in product.ingredient.benefits for concern in user.skin_concerns):
                recommended_product = product
                break  # Stop searching further products once a match is found
        user.recommended_product = recommended_product

def run_program():
    while True:
        choice = input("Do you want to add a user or a product? (user/product): ").strip().lower()
        if choice == 'user':
            add_new_user()
            print_all_users()
        elif choice == 'product':
            add_new_product()
            print_all_products()
        else:
            print("Invalid choice. Please enter 'user' or 'product'.")

        cont = input("Do you want to continue? (yes/no): ").strip().lower()
        if cont != 'yes':
            break

    recommend_products_to_users()

    # Ask user if they want to see recommended product and its fitting ingredient
    for user_name, user in users_dict.items():
        if user.recommended_product is not None:
            show_product = input(f"\n{user_name}, do you want to see the product and its fitting ingredient? (yes/no): ").strip().lower()
            if show_product == 'yes':
                print(f"\nProduct and its fitting ingredient for {user_name}:")
                print(f"   {user.recommended_product.name}: {user.recommended_product.ingredient.name}")
            else:
                print(f"\n{user_name} chose not to see the product and its fitting ingredient.")

# Run the program
run_program()


Do you want to add a user or a product? (user/product): user
Enter your name: ortal
Enter your age: 38
Enter your gender: female
Enter your skin type (e.g., oily, dry, combination): oily
Enter your skin concerns (comma separated, e.g., acne, hydration): acne
User ortal added successfully.
All Users Dictionary:
ortal: User(name=ortal, age=38, gender=female, skin_type=oily, skin_concerns=['acne'])
Do you want to continue? (yes/no): yes
Do you want to add a user or a product? (user/product): product
Enter the product name: aloe
Enter the product type: cream
Enter the ingredient name: alovera
Enter the benefits of the ingredient (comma separated): acne
Enter the recommended percentage of the ingredient: 80
Enter the max percentage of the ingredient: 100
Enter the percentage of alovera in the product: 90
Product aloe added successfully.
All Products Dictionary:
aloe: Product(name=aloe, product_type=cream, ingredient=Ingredient(name=alovera, benefits=['acne'], recommended_percentage=80.0, ma

KeyboardInterrupt: Interrupted by user

In [ ]:
class Ingredient:
    def __init__(self, name, benefits, recommended_percentage, max_percentage):
        self.name = name
        self.benefits = benefits
        self.recommended_percentage = recommended_percentage
        self.max_percentage = max_percentage

    def __repr__(self):
        return f"Ingredient(name={self.name}, benefits={self.benefits}, recommended_percentage={self.recommended_percentage}, max_percentage={self.max_percentage})"

class Product:
    def __init__(self, name, product_type):
        self.name = name
        self.product_type = product_type
        self.ingredients = []
        self.total_percentage = 0

    def add_ingredient(self, ingredient, percentage):
        if self.total_percentage + percentage <= 100:
            if percentage <= ingredient.max_percentage:
                self.ingredients.append((ingredient, percentage))
                self.total_percentage += percentage
            else:
                print(f"Error: Cannot add {ingredient.name} at {percentage}%. Max allowed is {ingredient.max_percentage}%.")
        else:
            print(f"Error: Total percentage exceeds 100%. Cannot add {ingredient.name}.")

    def calculate_benefit_score(self):
        benefits = []
        for ingredient, _ in self.ingredients:
            benefits.extend(ingredient.benefits)
        return benefits

    def addresses_skin_concern(self, skin_concern):
        for ingredient, _ in self.ingredients:
            if skin_concern in ingredient.benefits:
                return True
        return False

    def __repr__(self):
        return f"Product(name={self.name}, product_type={self.product_type}, ingredients={self.ingredients}, total_percentage={self.total_percentage})"

class User:
    def __init__(self, name, age, gender, skin_type, skin_concerns):
        self.name = name
        self.age = age
        self.gender = gender
        self.skin_type = skin_type
        self.skin_concerns = skin_concerns
        self.recommended_product = None

    def __repr__(self):
        return f"User(name={self.name}, age={self.age}, gender={self.gender}, skin_type={self.skin_type}, skin_concerns={self.skin_concerns})"

# Dictionaries to store users and products
users_dict = {}
products_dict = {}

def add_new_user():
    name = input("Enter your name: ")
    age = int(input("Enter your age: "))
    gender = input("Enter your gender: ")
    skin_type = input("Enter your skin type (e.g., oily, dry, combination): ")
    skin_concerns = input("Enter your skin concerns (comma separated, e.g., acne, hydration): ").split(", ")

    user = User(name, age, gender, skin_type, skin_concerns)
    users_dict[name] = user

    print(f"User {name} added successfully.")

def add_new_product():
    product_name = input("Enter the product name: ")
    product_type = input("Enter the product type: ")
    product = Product(product_name, product_type)

    while True:
        ingredient_name = input("Enter the ingredient name (or 'done' to finish): ")
        if ingredient_name.lower() == 'done':
            break
        benefits = input("Enter the benefits of the ingredient (comma separated): ").split(", ")
        recommended_percentage = float(input("Enter the recommended percentage of the ingredient: "))
        max_percentage = float(input("Enter the max percentage of the ingredient: "))

        ingredient = Ingredient(ingredient_name, benefits, recommended_percentage, max_percentage)
        percentage = float(input(f"Enter the percentage of {ingredient_name} in the product: "))
        product.add_ingredient(ingredient, percentage)

    products_dict[product_name] = product
    print(f"Product {product_name} added successfully.")

def print_all_users():
    print("All Users Dictionary:")
    for name, user in users_dict.items():
        print(f"{name}: {user}")

def print_all_products():
    print("All Products Dictionary:")
    for name, product in products_dict.items():
        print(f"{name}: {product}")

def recommend_products_to_users():
    for user_name, user in users_dict.items():
        user_products = []
        for product_name, product in products_dict.items():
            if any(concern in product.calculate_benefit_score() for concern in user.skin_concerns):
                user_products.append(product_name)
        user.recommended_product = user_products

def run_program():
    while True:
        choice = input("Do you want to add a user or a product? (user/product): ").strip().lower()
        if choice == 'user':
            add_new_user()
            print_all_users()
        elif choice == 'product':
            add_new_product()
            print_all_products()
        else:
            print("Invalid choice. Please enter 'user' or 'product'.")

        cont = input("Do you want to continue? (yes/no): ").strip().lower()
        if cont != 'yes':
            break

    recommend_products_to_users()

    # Ask user if they want to see recommended products
    for user_name, user in users_dict.items():
        if user.recommended_product:
            show_products = input(f"\n{user_name}, do you want to see products that fit your skin concerns? (yes/no): ").strip().lower()
            if show_products == 'yes':
                print(f"\nProducts fitting {user_name}'s skin concerns:")
                for product_name in user.recommended_product:
                    print(f"   Product: {product_name}")
            else:
                print(f"\n{user_name} chose not to see products fitting their skin concerns.")

# Run the program
run_program()


Do you want to add a user or a product? (user/product): user
Enter your name: ortal
Enter your age: 38
Enter your gender: female
Enter your skin type (e.g., oily, dry, combination): oily
Enter your skin concerns (comma separated, e.g., acne, hydration): acne
User ortal added successfully.
All Users Dictionary:
ortal: User(name=ortal, age=38, gender=female, skin_type=oily, skin_concerns=['acne'])
Do you want to continue? (yes/no): yes
Do you want to add a user or a product? (user/product): product
Enter the product name: aloe
Enter the product type: cream
Enter the ingredient name (or 'done' to finish): alovera
Enter the benefits of the ingredient (comma separated): acne
Enter the recommended percentage of the ingredient: 80
Enter the max percentage of the ingredient: 100
Enter the percentage of alovera in the product: 85
Enter the ingredient name (or 'done' to finish): done
Product aloe added successfully.
All Products Dictionary:
aloe: Product(name=aloe, product_type=cream, ingredient

KeyboardInterrupt: Interrupted by user

In [ ]:
#PLEASE RUN THIS CODE BLOCK ONLY

from dataclasses import dataclass, field

class Ingredient: #creating ingredient object which is the main ingredient inside a product, which gives a benefit to a certain skin concern (benefit = skin concern)
    def __init__(self, name, benefits, recommended_percentage, max_percentage): #initializing classes using the __init__ method.
        self.name = name
        self.benefits = benefits #benefit
        self.recommended_percentage = recommended_percentage #the percentage of the ingredient inside a product.
        self.max_percentage = max_percentage

    def __repr__(self): #printing the ingredients into the console using __repr__ method and f string
        return f"Ingredient(name={self.name}, benefits={self.benefits}, recommended_percentage={self.recommended_percentage}, max_percentage={self.max_percentage})"

class Product: #creating product object, in this code it relates to cosmetic product that benefit a certain skin concern
    def __init__(self, name, product_type):
        self.name = name
        self.product_type = product_type #what type the product is (for example: cream, etc.)
        self.ingredients = []
        self.total_percentage = 0

    def add_ingredient(self, ingredient, percentage):#a function which add an ingredient to the list of ingredients inside a product
        if self.total_percentage + percentage <= 100:
            if percentage <= ingredient.max_percentage:
                self.ingredients.append((ingredient, percentage))
                self.total_percentage += percentage
            else:
                print(f"Error: Cannot add {ingredient.name} at {percentage}%. Max allowed is {ingredient.max_percentage}%.")
        else:
            print(f"Error: Total percentage exceeds 100%. Cannot add {ingredient.name}.")

    def calculate_benefit_score(self): #this function adds a benefit to an ingredient, meaning the ingredient can benefit/improve a ceratin skin concern.
        benefits = []
        for ingredient, _ in self.ingredients:
            benefits.extend(ingredient.benefits)
        return benefits

    def __repr__(self): #printing the products into the console, and inside we print the ingredients of that product.
        return f"Product(name={self.name}, product_type={self.product_type}, ingredients={self.ingredients}, total_percentage={self.total_percentage})"

class User: #creating user object with his details and skin concern (which later on should pick up the matching corresponding benefit)
    def __init__(self, name, age, gender, skin_type, skin_concerns):
        self.name = name
        self.age = age
        self.gender = gender
        self.skin_type = skin_type
        self.skin_concerns = skin_concerns #skin concern
        self.recommended_products = [] #the list of the products which will be recommended to the user according the match benefit = skin concern.

    def __repr__(self): #printing the details of the user
        return f"User(name={self.name}, age={self.age}, gender={self.gender}, skin_type={self.skin_type}, skin_concerns={self.skin_concerns})"

# Dictionaries to store users and products
users_dict = {}
products_dict = {}

def add_new_user(): #this function is adding new users instances to the users dictionary
    name = input("Enter your name: ")
    age = int(input("Enter your age: "))
    gender = input("Enter your gender: ")
    skin_type = input("Enter your skin type (e.g., oily, dry, combination): ")
    skin_concerns = input("Enter your skin concerns (comma separated, e.g., acne, hydration): ").split(", ")

    user = User(name, age, gender, skin_type, skin_concerns)
    users_dict[name] = user

    print(f"User {name} added successfully.") #validation

def add_new_product(): #this function adds a new product to the products dictionary
    product_name = input("Enter the product name: ")
    product_type = input("Enter the product type: ")
    product = Product(product_name, product_type)

    while True: #using while loop (flow control) for prompting input related to an ingredient
        ingredient_name = input("Enter the ingredient name (or 'done' to finish): ")
        if ingredient_name.lower() == 'done':
            break
        benefits = input("Enter the benefits of the ingredient (comma separated): ").split(", ")
        recommended_percentage = float(input("Enter the recommended percentage of the ingredient: "))
        max_percentage = float(input("Enter the max percentage of the ingredient: "))

        ingredient = Ingredient(ingredient_name, benefits, recommended_percentage, max_percentage)
        percentage = float(input(f"Enter the percentage of {ingredient_name} in the product: "))
        product.add_ingredient(ingredient, percentage)

    products_dict[product_name] = product
    print(f"Product {product_name} added successfully.") #validation

def print_all_users(): #this function creats a dictionary of users by users names as keys and user details as values
    print("All Users Dictionary:")
    for name, user in users_dict.items():
        print(f"{name}: {user}")

def print_all_products(): #this function creates a dictionary of products by products names as keys and products details as values
    print("All Products Dictionary:")
    for name, product in products_dict.items():
        print(f"{name}: {product}")

def recommend_products_to_users(): #this function creates a list of user products that are recommended for the user using the concern iterable in the list comprehension using "any".
    for user_name, user in users_dict.items(): #tupeling
        user_products = []
        for product_name, product in products_dict.items(): #tupeling
            if any(concern in product.calculate_benefit_score() for concern in user.skin_concerns):
                user_products.append(product_name)
        user.recommended_products = user_products

def get_products_benefits_dict(): #this function creates a dictionary of benefits by extracting these values from the products dictionary
    products_benefits_dict = {}
    for product_name, product in products_dict.items():
        products_benefits_dict[product_name] = product.calculate_benefit_score() #creating a dictionary of products names as keys and benefits as values
    return products_benefits_dict

def get_users_skin_concerns_dict(): #this function creates a dictionary of skin concerns by extracting these values from the users dictionary
    users_skin_concerns_dict = {}
    for user_name, user in users_dict.items():
        users_skin_concerns_dict[user_name] = user.skin_concerns #creating a dictionary of users names as keys and skin concerns as values
    return users_skin_concerns_dict

def compare_benefits_and_concerns(): #this function compares between the poducts benefits dictionary to the user skin concerns dictionary
    products_benefits_dict = get_products_benefits_dict()
    users_skin_concerns_dict = get_users_skin_concerns_dict()

    comparison_results = {}
    for user_name, skin_concerns in users_skin_concerns_dict.items():
        matching_products = []
        for product_name, benefits in products_benefits_dict.items():
            if any(concern in benefits for concern in skin_concerns):
                matching_products.append(product_name)
        comparison_results[user_name] = matching_products #creating a dictionary of users name and matching products by comparing between the values of benefits and skin concerns.

    return comparison_results

def run_program():#this function runs the program by prompting it by inputs
    while True:
        choice = input("Do you want to add a user or a product? (user/product): ").strip().lower()
        if choice == 'user':
            add_new_user()
            print_all_users()
        elif choice == 'product':
            add_new_product()
            print_all_products()
        else:
            print("Invalid choice. Please enter 'user' or 'product'.")

        cont = input("Do you want to continue? (yes/no): ").strip().lower()
        if cont != 'yes':
            break

    recommend_products_to_users()

    # Ask user if they want to see recommended products
    for user_name, user in users_dict.items():
        if user.recommended_products:
            show_products = input(f"\n{user_name}, do you want to see products that fit your skin concerns? (yes/no): ").strip().lower()
            if show_products == 'yes':
                print(f"\nProducts fitting {user_name}'s skin concerns:")
                for product_name in user.recommended_products:
                    product = products_dict[product_name]
                    print(f"   Product: {product_name}")
                    for ingredient, _ in product.ingredients:
                        print(f"      Ingredient: {ingredient.name}, Benefits: {ingredient.benefits}")
            else:
                print(f"\n{user_name} chose not to see products fitting their skin concerns.")

    # Print the products benefits dictionary, used for validation
    products_benefits_dict = get_products_benefits_dict()
    print("\nProducts and their benefits:")
    for product_name, benefits in products_benefits_dict.items():
        print(f"   Product: {product_name}, Benefits: {benefits}")

    # Print the users skin concerns dictionary, used for validation
    users_skin_concerns_dict = get_users_skin_concerns_dict()
    print("\nUsers and their skin concerns:")
    for user_name, skin_concerns in users_skin_concerns_dict.items():
        print(f"   User: {user_name}, Skin Concerns: {skin_concerns}")

    # Compare benefits and concerns and print comparison results - this is the goal of the program
    comparison_results = compare_benefits_and_concerns()
    print("\nComparison of benefits and skin concerns:")
    for user_name, matching_products in comparison_results.items():
        print(f"   User: {user_name}, Matching Products: {matching_products}")

    # Print the new dictionary with user names as keys and product names as values - this is also another goal - to recieve new dictionary storing all users data including matching products for future storing and data analizing
    user_products_dict = {}
    for user_name, matching_products in comparison_results.items():
        user_products_dict[user_name] = matching_products

    print("\nUser to Products Matching Dictionary:")
    for user_name, products in user_products_dict.items():
        print(f"   User: {user_name}, Products: {products}")

# Run the program
run_program()

Product Harta added successfully.
All Products Dictionary:
Harta: Product(name=Harta, product_type=Barta, ingredients=[(Ingredient(name=ddd, benefits=['a,b,c'], recommended_percentage=-12.0, max_percentage=-44.0), -2313.0)], total_percentage=-2313.0)


Example of how the results looks like after prompting the last block (no need to run the other blocks, they were used as increments during the develop of this program) -

Do you want to add a user or a product? (user/product): user

Enter your name: ortal

Enter your age: 38

Enter your gender: female

Enter your skin type (e.g., oily, dry, combination): oily

Enter your skin concerns (comma separated, e.g., acne, hydration): acne

User ortal added successfully.

All Users Dictionary:

ortal: User(name=ortal, age=38, gender=female, skin_type=oily, skin_concerns=['acne'])

Do you want to continue? (yes/no): yes

Do you want to add a user or a product? (user/product): products

Invalid choice. Please enter 'user' or 'product'.

Do you want to continue? (yes/no): yes

Do you want to add a user or a product? (user/product): product

Enter the product name: aloe

Enter the product type: cream

Enter the ingredient name (or 'done' to finish): alovera

Enter the benefits of the ingredient (comma separated): acne

Enter the recommended percentage of the ingredient: 80

Enter the max percentage of the ingredient: 100

Enter the percentage of alovera in the product: 85

Enter the ingredient name (or 'done' to finish): done

Product aloe added successfully.

All Products Dictionary:

aloe: Product(name=aloe, product_type=cream, ingredients=[(Ingredient(name=alovera, benefits=['acne'], recommended_percentage=80.0, max_percentage=100.0), 85.0)], total_percentage=85.0)

Do you want to continue? (yes/no): yes

Do you want to add a user or a product? (user/product): user

Enter your name: rona

Enter your age: 1

Enter your gender: female

Enter your skin type (e.g., oily, dry, combination): dry

Enter your skin concerns (comma separated, e.g., acne, hydration): hydration

User rona added successfully.

All Users Dictionary:

ortal: User(name=ortal, age=38, gender=female, skin_type=oily, skin_concerns=['acne'])

rona: User(name=rona, age=1, gender=female, skin_type=dry, skin_concerns=['hydration'])

Do you want to continue? (yes/no): no

ortal, do you want to see products that fit your skin concerns? (yes/no): yes

Products fitting ortal's skin concerns:

   Product: aloe

      Ingredient: alovera, Benefits: ['acne']

Products and their benefits:

   Product: aloe, Benefits: ['acne']

Users and their skin concerns:

   User: ortal, Skin Concerns: ['acne']

   User: rona, Skin Concerns: ['hydration']

Comparison of benefits and skin concerns:

   User: ortal, Matching Products: ['aloe']

   User: rona, Matching Products: []

User to Products Matching Dictionary:

   User: ortal, Products: ['aloe']

   User: rona, Products: []